version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOBASE=${GOPATH}
        - TARGETS=${TARGET_CNT:-1000}
        - CLDPROVIDER=${CLDPROVIDER}
        - NODISKIO=${NODISKIO}
        - NONETIO=${NONETIO}
        - DRYOBJSIZE=${DRYOBJSIZE}
    networks:
        public:
    environment:
      - ROLE=proxy
      - AIS_PRIMARYPROXY=${AIS_PRIMARYPROXY}
    env_file:
      - /tmp/docker_ais/aws.env
    volumes:
      - ${GOPATH}/src:${GOPATH}/src
      - ${HOST_CONTAINER_PATH}:/tmp/ais
  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOBASE=${GOPATH}
        - TARGETS=${TARGET_CNT:-1000}
        - CLDPROVIDER=${CLDPROVIDER}
        - NODISKIO=${NODISKIO}
        - NONETIO=${NONETIO}
        - DRYOBJSIZE=${DRYOBJSIZE}
    networks:
        public:
    environment:
      - ROLE=target
    env_file:
      - /tmp/docker_ais/aws.env
    volumes:
      - ${GOPATH}/src:${GOPATH}/src
      - ${HOST_CONTAINER_PATH}:/tmp/ais
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: ${PUB_SUBNET}
