---
- hosts: all 
  gather_facts: no
  tasks:
    - copy:
        src: "{{ playbook_dir }}/configais.sh"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - copy:
        src: "{{ playbook_dir }}/inventory"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      shell: /home/ubuntu/configais.sh
...

