---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Compress ais logs
      archive:
        path: /var/log/ais
        dest: /tmp/log.tgz
    - fetch:
        src: /tmp/log.tgz
        dest: "{{ playbook_dir }}/logs/{{ inventory_hostname }}/log.tgz"
        flat: yes
        serial: 100%

